name: Remove Contributor History

on:
  workflow_dispatch:  # Manual trigger

jobs:
  remove-contributor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history needed

      - name: Install Java (required for BFG)
        run: sudo apt-get update && sudo apt-get install -y openjdk-11-jre-headless

      - name: Download BFG Repo Cleaner
        run: |
          curl -L -o bfg.jar https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar

      - name: Remove Contributor
        run: |
          java -jar bfg.jar --delete-users someone@example.com .
        
      - name: Cleanup Repository
        run: |
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

      - name: Force Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --force

      - name: Success
        run: echo "Contributor removed and history cleaned successfully."
